on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics
