name: Linter

on:
  push:
    branches:
      - master
      - 'dev-**'
  pull_request:
    branches:
      - master
      - 'dev-**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Check flake8
        run: python -m flake8 . --count --show-source --statistics --append-config .flake8
